### ISSUE TITLE
Nothing happens after login

### ISSUE THREAD

**Issue by MCKapur** [DotMail/DotMail#21]
After I provide my login details, I get this view: http://cl.ly/image/3O0e223G0h2H - but it appears to be frozen there. When I quit/reopen, I get the message "DotMail cannot be opened because of a problem".

REPORT:
==============

Process:         DotMail [11900]
Path:            /Users/USER/Library/Developer/Xcode/DerivedData/DotMail-bjbtqhpeofihnreehpwfyfcebojt/Build/Products/Debug/DotMail.app/Contents/MacOS/DotMail
Identifier:      com.codafi.dotmail
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [198]
Responsible:     DotMail [11900]
User ID:         501

Date/Time:       2014-02-01 17:30:49.683 +0800
OS Version:      Mac OS X 10.9 (13A598)
Report Version:  11
Anonymous UUID:  FF540F81-AEFF-381C-2754-DD929795CBE0

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/MailCore.framework/Versions/A/MailCore
  Referenced from: /Users/USER/Library/Developer/Xcode/DerivedData/DotMail-bjbtqhpeofihnreehpwfyfcebojt/Build/Products/Debug/DotMail.app/Contents/MacOS/DotMail
  Reason: image not found

Binary Images:
    0x7fff64899000 -     0x7fff648cc817  dyld (239.3) <D1DFCF3F-0B0C-332A-BCC0-87A851B570FF> /usr/lib/dyld
    0x7fff82d39000 -     0x7fff82d39fff  com.apple.ApplicationServices (48 - 48) <3E3F01A8-314D-378F-835E-9CC4F8820031> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff833fb000 -     0x7fff834dafff  libcrypto.0.9.8.dylib (50) <B95B9DBA-39D3-3EEF-AF43-44608B28894E> /usr/lib/libcrypto.0.9.8.dylib
    0x7fff840d4000 -     0x7fff84125fff  com.apple.QuickLookFramework (5.0 - 622.3) <AB6CCD09-ECDF-3F01-9C42-34B37DDCF12D> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff84126000 -     0x7fff84126fff  com.apple.Cocoa (6.8 - 20) <E90E99D7-A425-3301-A025-D9E0CD11918E> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff84b4c000 -     0x7fff84d8ffff  com.apple.AddressBook.framework (8.0 - 1365) <816242B1-D45E-3B5D-BC98-BB23458D5367> /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
    0x7fff8782a000 -     0x7fff879c6ff7  com.apple.QuartzCore (1.8 - 332.0) <994D1E0A-64B6-398C-B9A2-C362F02DE943> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff879da000 -     0x7fff87c32ff1  com.apple.security (7.0 - 55471) <233831C5-C457-3AD5-AFE7-E3E2DE6929C9> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff8ad14000 -     0x7fff8adfbff7  libxml2.2.dylib (26) <A1DADD11-89E5-3DE4-8802-07186225967F> /usr/lib/libxml2.2.dylib
    0x7fff8c624000 -     0x7fff8c624fff  com.apple.quartzframework (1.5 - 1.5) <3B2A72DB-39FC-3C5B-98BE-605F37777F37> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff8c917000 -     0x7fff8c981ff7  com.apple.framework.IOKit (2.0.1 - 907.1.13) <C1E95F5C-B79B-31BE-9F2A-1B25163C1F16> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff8d8c4000 -     0x7fff8d986ff1  com.apple.CoreText (352.0 - 367.15) <E5C70FC8-C861-39B8-A491-595E5B55CFC8> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff8f6ef000 -     0x7fff8f824ffa  com.apple.WebKit (9537 - 9537.71) <8A07478D-B2CA-3724-81E4-ADC10E1AD3EA> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit

**Comment by CodaFi** [comment]
Reopen this issue if you have any further updates.
